FROM python:2.7

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

COPY dist/skipper_example-1.0.0.tar.gz /tmp/skipper_example-1.0.0.tar.gz
RUN pip install /tmp/skipper_example-1.0.0.tar.gz

ENV FLASK_APP=skipper_example.main

ENTRYPOINT flask run --host=0.0.0.0
